/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:a1495f35-571d-4d3d-b3fa-ecd058140a76",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_D9o82HVlA",
    "aws_user_pools_web_client_id": "2i4pq6pc9k1el285pnb4b4s0vo",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://zai525u3tzbwzmu43tpy7sgrpq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "masterarbeit5521fc868adc450bb95108f7b72339a494223-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
